
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.0.9"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/naoina/denco"

[[constraint]]
  branch = "master"
  name = "github.com/naoina/genmai"

[[constraint]]
  name = "github.com/naoina/go-stringutil"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/naoina/miyabi"

[[constraint]]
  branch = "master"
  name = "github.com/ugorji/go"

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
