// generated by stringer -type Level; DO NOT EDIT

package log

import "fmt"

const _Level_name = "NONEDEBUGINFOWARNERRORFATALPANIC"

var _Level_index = [...]uint8{0, 4, 9, 13, 17, 22, 27, 32}

func (i Level) String() string {
	if i+1 >= Level(len(_Level_index)) {
		return fmt.Sprintf("Level(%d)", i)
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
