package controllers

import (
	"github.com/naoina/kocha"
)

type {{.Name}} struct {
	*kocha.Controller
}

func (c *{{.Name}}) Get() kocha.Result {
	// FIXME: auto-generated by kocha
	return c.Render()
}

func (c *{{.Name}}) Post() kocha.Result {
	// FIXME: auto-generated by kocha
	return c.Render()
}
